## Student Placement Prediction

- **This project is about predicting whether a student will be placed or not based on various features**

*Importing Liabraries*

In [137]:
import pandas as pd
import numpy as np
import seaborn as sns

In [138]:
# loading the dataset 
df = pd.read_csv("C:\\Users\\Admin\\Downloads\\college_student_placement_dataset.csv", header=0)
df_backup = df.copy() # creating a backup of the dataset

In [139]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [140]:
# describe the dataset EDA 
df.describe() # numerical features

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [141]:
# finding the null values in the dataset
df.isna().sum() # no null values

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [142]:
# infomration about dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [143]:
# checking the duplicate values in the dataset
df.duplicated().sum()# no duplicate values

np.int64(0)

*Here in the above dataset there is some features which are not required for the prediction so we will drop those features and keep only the required features for the prediction*

In [144]:
# delete college_ID column 
df = df.drop('College_ID', axis=1)

In [145]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,No
1,97,5.52,5.37,8,No,7,8,0,No
2,109,5.36,5.83,9,No,3,1,1,No
3,122,5.47,5.75,6,Yes,1,6,1,No
4,96,7.91,7.69,7,No,8,10,2,No

In [146]:
# dummy encoding the categorical features alternative of one hot encoding
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df['Placement'] = le.fit_transform(df['Placement']) # this convert the categories into numnerical yes = 1 and no = 0

In [147]:
for col in df.select_dtypes(include='object').columns:
    dummies = pd.get_dummies(df[col], prefix=col, drop_first=True).astype(int)

In [148]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,0
1,97,5.52,5.37,8,No,7,8,0,0
2,109,5.36,5.83,9,No,3,1,1,0
3,122,5.47,5.75,6,Yes,1,6,1,0
4,96,7.91,7.69,7,No,8,10,2,0

In [149]:
dummies.head() # only the interenship coulumn is categorical its made dummy variable for it

   Internship_Experience_Yes
0                          0
1                          0
2                          0
3                          1
4                          0

In [150]:
# removing the original categorical column and adding the dummy variable column to the dataset
df = df.drop('Internship_Experience', axis=1)
# add dummy col to dataframe 
df = pd.concat([df, dummies], axis=1)

In [151]:
df.tail()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Internship_Experience_Yes
9995,119,8.41,8.29,4,1,8,0,1,0
9996,70,9.25,9.34,7,0,7,2,0,0
9997,89,6.08,6.25,3,3,9,5,0,1
9998,107,8.77,8.92,3,7,5,1,0,0
9999,109,9.41,9.77,8,3,5,5,0,0

In [152]:
df.head() # now the dataste is ready for the model

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Internship_Experience_Yes
0,107,6.61,6.28,8,8,8,4,0,0
1,97,5.52,5.37,8,7,8,0,0,0
2,109,5.36,5.83,9,3,1,1,0,0
3,122,5.47,5.75,6,1,6,1,0,1
4,96,7.91,7.69,7,8,10,2,0,0

- splitting the dataset

In [153]:
x = df.drop('Placement', axis=1) # dependent variable 
y = df['Placement'] # independent variable

In [154]:
x.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Internship_Experience_Yes
0,107,6.61,6.28,8,8,8,4,0
1,97,5.52,5.37,8,7,8,0,0
2,109,5.36,5.83,9,3,1,1,0
3,122,5.47,5.75,6,1,6,1,1
4,96,7.91,7.69,7,8,10,2,0

In [155]:
# importing liabraries for model building
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, matthews_corrcoef

In [156]:
# splitting the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

- Standardizing the dataset

In [157]:
scaler = StandardScaler() 
x_train_scale = scaler.fit_transform(x_train)
x_test_scale = scaler.transform(x_test)

- *Building the model*

**XGBoost Classifier**

In [168]:
from xgboost import XGBClassifier 
# here is model with regularization parameters because model is making more importance to the specfic features
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42
)
xgb.fit(x_train, y_train)

y_pred_train = xgb.predict(x_train)
y_pred_test = xgb.predict(x_test)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))
print('Mathews correlation coefficient:- ',matthews_corrcoef(y_train, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))
print('Mathews correlation coefficient:- ',matthews_corrcoef(y_test, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6667
           1       1.00      1.00      1.00      1333

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

confusion_matrix:-  [[6667    0]
 [   0 1333]]
accuracy_score:-  1.0
Mathews correlation coefficient:-  1.0
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

confusion_matrix:-  [[1674    0]
 [   0  326]]
accuracy_score:-  1.0
Mathews correlation coefficient:-  1.0

In [169]:
# showing the feature importance of the model
print(xgb.feature_importances_)

[0.29213253 0.16788319 0.13710652 0.         0.01352004 0.21214736
 0.17721033 0.        ]

**Logistic Regression**

In [158]:
from sklearn.linear_model import LogisticRegression 

lg = LogisticRegression()
lg.fit(x_train_scale, y_train)

y_pred_train = lg.predict(x_train_scale)
y_pred_test = lg.predict(x_test_scale)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       0.92      0.96      0.94      6667
           1       0.76      0.61      0.67      1333

    accuracy                           0.90      8000
   macro avg       0.84      0.78      0.81      8000
weighted avg       0.90      0.90      0.90      8000

confusion_matrix:-  [[6405  262]
 [ 521  812]]
accuracy_score:-  0.902125
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       0.93      0.96      0.94      1674
           1       0.75      0.61      0.67       326

    accuracy                           0.90      2000
   macro avg       0.84      0.78      0.81      2000
weighted avg       0.90      0.90      0.90      2000

confusion_matrix:-  [[1609   65]
 [ 128  198]]
accuracy_score:-  0.9035

**Decision Tree Classifier**

In [159]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(min_samples_split=3, min_samples_leaf=4 ,random_state=42)
dt.fit(x_train, y_train)

y_pred_train = dt.predict(x_train)
y_pred_test= dt.predict(x_test)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6667
           1       1.00      1.00      1.00      1333

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

confusion_matrix:-  [[6667    0]
 [   0 1333]]
accuracy_score:-  1.0
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

confusion_matrix:-  [[1674    0]
 [   0  326]]
accuracy_score:-  1.0

**Random Forest Classifier**

In [176]:
# Random Forest is the best model for this dataset as it gives the best accuracy and feature importance
from sklearn.ensemble import RandomForestClassifier 
import joblib 

rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, y_train)

# Saving the model 
joblib.dump(rf, 'placement_predictor.joblib')

y_pred_train = rf.predict(x_train)
y_pred_test = rf.predict(x_test)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))
print('Mathews correlation coefficient:- ',matthews_corrcoef(y_train, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))
print('Mathews correlation coefficient:- ',matthews_corrcoef(y_test, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6667
           1       1.00      1.00      1.00      1333

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

confusion_matrix:-  [[6667    0]
 [   0 1333]]
accuracy_score:-  1.0
Mathews correlation coefficient:-  1.0
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

confusion_matrix:-  [[1674    0]
 [   0  326]]
accuracy_score:-  1.0
Mathews correlation coefficient:-  1.0

- All the metrics are calculated for 'Random Forest Classifier' as it is giving the best accuracy score among all the models built.

**LDA**

In [89]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(x_train_scale, y_train)

y_pred_train = lda.predict(x_train_scale)
y_pred_test = lda.predict(x_test_scale)

# for training data 
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))

# for testing data 
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))

Classification Report:-
               precision    recall  f1-score   support

           0       0.91      0.97      0.94      6667
           1       0.80      0.55      0.65      1333

    accuracy                           0.90      8000
   macro avg       0.86      0.76      0.80      8000
weighted avg       0.89      0.90      0.89      8000

confusion_matrix:-  [[6480  187]
 [ 605  728]]
accuracy_score:-  0.901
classification_report:-
               precision    recall  f1-score   support

           0       0.92      0.97      0.94      1674
           1       0.78      0.55      0.64       326

    accuracy                           0.90      2000
   macro avg       0.85      0.76      0.79      2000
weighted avg       0.89      0.90      0.89      2000

confusion_matrix:-  [[1623   51]
 [ 148  178]]
accuracy_score:-  0.9005

**Bagging Classifier**

In [90]:
from sklearn.ensemble import BaggingClassifier

bg = BaggingClassifier(n_estimators=100, random_state=42, n_jobs=-1)
bg.fit(x_train, y_train)

y_pred_train = bg.predict(x_train)
y_pred_test = bg.predict(x_test)

# for training data 
print('Classification Report:- \n',classification_report(y_train, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_train, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_train, y_pred_train))

# for testing data 
print('classification_report:- \n',classification_report(y_test, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_test, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_test, y_pred_test))

Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6667
           1       1.00      1.00      1.00      1333

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

confusion_matrix:-  [[6667    0]
 [   0 1333]]
accuracy_score:-  1.0
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

confusion_matrix:-  [[1674    0]
 [   0  326]]
accuracy_score:-  1.0

- *K Fold Cross Validation*

In [91]:
from sklearn.model_selection import StratifiedKFold, cross_val_score # this kFold shows actual accuracy of the model

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(rf, x_train_scale, y_train, cv=cv, scoring='accuracy')
print("Cross-validation scores: ", scores)
print("Mean CV score: ", scores.mean())

Cross-validation scores:  [1.       1.       0.999375 1.       1.      ]
Mean CV score:  0.9998750000000001

In [177]:
rf.feature_importances_

array([0.24867356, 0.11102288, 0.16185725, 0.01073471, 0.01076237,
       0.27283601, 0.18130946, 0.00280377])

In [93]:
dt.feature_importances_

array([0.21444485, 0.        , 0.32150214, 0.        , 0.        ,
       0.1731492 , 0.29090382, 0.        ])

In [94]:
test = [[80, 6.41, 6.28, 8, 8, 8, 8, 0]]
import joblib 
model = joblib.load('placement_predictor.joblib')
print(model.predict(test))

[0]

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [95]:
print(lg.predict(test))

[1]

In [96]:
print(lda.predict(test))

[1]

In [97]:
y_train.value_counts() # this shows the number of students who got placed and who did not get placed in the dataset. 1 means placed and 0 means not placed. The dataset is imbalanced as there are more students who got placed than those who did not get placed. This can affect the model's performance.

Placement
0    6667
1    1333
Name: count, dtype: int64

In [98]:
df['Placement'].value_counts()

Placement
0    8341
1    1659
Name: count, dtype: int64

In [99]:
print(dt.predict(test))

[0]

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [100]:
x.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Internship_Experience_Yes
0,107,6.61,6.28,8,8,8,4,0
1,97,5.52,5.37,8,7,8,0,0
2,109,5.36,5.83,9,3,1,1,0
3,122,5.47,5.75,6,1,6,1,1
4,96,7.91,7.69,7,8,10,2,0

In [101]:
test2 = [[119, 8.41, 8.29, 4, 1, 8, 0, 0]]
print(bg.predict(test2))

[1]

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(

### making new dataset with balanced classes

In [102]:
yes = df[df['Placement'] == 1] # placed studeents

In [103]:
yes.shape

(1659, 9)

In [104]:
yes.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Internship_Experience_Yes
6,123,6.68,6.58,5,7,8,2,1,0
7,111,8.77,8.76,7,3,1,2,1,0
18,86,8.20,8.15,7,8,9,4,1,0
20,121,8.41,8.07,5,1,3,3,1,1
23,78,8.67,9.17,7,10,10,2,1,1

In [105]:
no = df[df['Placement'] == 0] # not placed students
no_back = no.copy() # copy of no dataset

In [106]:
no.shape

(8341, 9)

In [107]:
no.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Internship_Experience_Yes
0,107,6.61,6.28,8,8,8,4,0,0
1,97,5.52,5.37,8,7,8,0,0,0
2,109,5.36,5.83,9,3,1,1,0,0
3,122,5.47,5.75,6,1,6,1,0,1
4,96,7.91,7.69,7,8,10,2,0,0

In [108]:
n = no[:1000] # taking last 1000 rows of the not placed students dataset  
n_x = n.drop('Placement', axis=1) # independent variable
n_y = n['Placement'] # dependent variable

In [109]:
no = no.sample(n=2000, random_state=42) # taking a sample of 2000 students 'not placed' to balance the dataset

In [110]:
no.shape

(2000, 9)

In [111]:
data = pd.concat([yes, no], axis=0) # combining the placed and not placed students to create a balanced dataset

In [112]:
data.shape

(3659, 9)

In [113]:
# shuffle the dataset 
data = data.sample(frac=1, random_state=42).reset_index(drop=True) # shuffling the data and reset index from 0 to n-1

In [114]:
data.tail(15) # now the dataset is balanced with equal number of placed and not placed students. This will help the model to learn better and give better accuracy.

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Internship_Experience_Yes
3644,87,8.35,8.19,4,8,5,3,0,0
3645,94,8.47,8.69,5,0,7,1,0,1
3646,112,8.35,7.97,7,5,8,3,1,0
3647,112,8.58,8.93,1,2,9,4,1,1
3648,109,9.77,10.04,8,4,8,3,1,0
3649,111,7.64,7.92,5,7,9,3,1,1
3650,89,6.50,6.91,10,3,3,1,0,0
3651,97,8.86,8.78,6,10,8,4,1,0
3652,78,6.27,6.72,9,0,10,2,0,1
3653,121,8.67,9.03,8,10,10,5,1,0
3654,114,5.41,5.03,9,2,9,4,1,0
3655,142,8.20,8.63,4,1,7,2,1,0
3656,118,9.66,9.35,3,0,8,4,1,1
3657,87,8.06,7.96,5,3,6,5,0,0
3658,54,9.07,9.27,7,5,7,4,0,1

In [115]:
#data = data.drop('Communication_Skills', axis=1) # dropping the communication skills column as it is not important for the model and it is also a categorical variable which is not suitable for the model.
X = data.drop('Placement', axis=1) # dependent variable 
Y = data['Placement'] # independent variable

In [116]:
x_tr, x_te, y_tr, y_te = train_test_split(X, Y, test_size=0.2, random_state=42, shuffle=True, stratify=Y) 
# stratify = Y means that split the data in such a way that the division of the classes in the training and testing data is same as that of the original dataset.

In [60]:
# logistic regression model 
from sklearn.pipeline import Pipeline # for pipeline model building
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
model = Pipeline([
    ("polynomial", PolynomialFeatures(degree=2, include_bias=False)),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000))
])
model.fit(x_tr, y_tr)

y_pred_train = model.predict(x_tr)
y_pred_test= model.predict(x_te)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_tr, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_tr, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_tr, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_te, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_te, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_te, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       0.91      0.90      0.91      1600
           1       0.88      0.90      0.89      1327

    accuracy                           0.90      2927
   macro avg       0.90      0.90      0.90      2927
weighted avg       0.90      0.90      0.90      2927

confusion_matrix:-  [[1442  158]
 [ 136 1191]]
accuracy_score:-  0.8995558592415442
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       0.89      0.90      0.89       400
           1       0.87      0.87      0.87       332

    accuracy                           0.88       732
   macro avg       0.88      0.88      0.88       732
weighted avg       0.88      0.88      0.88       732

confusion_matrix:-  [[358  42]
 [ 43 289]]
accuracy_score:-  0.8838797814207651

In [118]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    model, x_te, y_te,
    n_repeats=10, random_state=42
)

for i in range(x_te.shape[1]):
    print(x_te.columns[i], result.importances_mean[i])

IQ 0.20273224043715848
Prev_Sem_Result 0.0
CGPA 0.20068306010928963
Academic_Performance 0.0
Extra_Curricular_Score 0.0
Communication_Skills 0.2125683060109289
Projects_Completed 0.11830601092896176
Internship_Experience_Yes 0.0

In [119]:
test = [[122, 7, 6.5, 4, 5, 6, 3, 0]]
print(model.predict(test))

[0]

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [120]:
dt = DecisionTreeClassifier(max_depth=5, min_samples_leaf=5,random_state=42)
dt.fit(x_tr, y_tr)

y_pred_train = dt.predict(x_tr)
y_pred_test= dt.predict(x_te)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_tr, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_tr, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_tr, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_te, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_te, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_te, y_pred_test))

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1600
           1       1.00      1.00      1.00      1327

    accuracy                           1.00      2927
   macro avg       1.00      1.00      1.00      2927
weighted avg       1.00      1.00      1.00      2927

confusion_matrix:-  [[1600    0]
 [   0 1327]]
accuracy_score:-  1.0
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       400
           1       1.00      1.00      1.00       332

    accuracy                           1.00       732
   macro avg       1.00      1.00      1.00       732
weighted avg       1.00      1.00      1.00       732

confusion_matrix:-  [[400   0]
 [  0 332]]
accuracy_score:-  1.0

In [131]:
rf = RandomForestClassifier(n_estimators=200, max_depth=5, min_samples_leaf=5, min_samples_split=10, random_state=42)
rf.fit(x_tr, y_tr)

y_pred_train = rf.predict(x_tr)
y_pred_test= rf.predict(x_te)

# for training data 
print('For Training')
print('Classification Report:- \n',classification_report(y_tr, y_pred_train))
print("confusion_matrix:- ", confusion_matrix(y_tr, y_pred_train))
print("accuracy_score:- ",accuracy_score(y_tr, y_pred_train))

# for testing data 
print('For Testing')
print('classification_report:- \n',classification_report(y_te, y_pred_test))
print('confusion_matrix:- ', confusion_matrix(y_te, y_pred_test))
print('accuracy_score:- ',accuracy_score(y_te, y_pred_test))
print("Feature importances: ", rf.feature_importances_)

For Training
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1600
           1       1.00      1.00      1.00      1327

    accuracy                           1.00      2927
   macro avg       1.00      1.00      1.00      2927
weighted avg       1.00      1.00      1.00      2927

confusion_matrix:-  [[1600    0]
 [   0 1327]]
accuracy_score:-  1.0
For Testing
classification_report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       400
           1       1.00      1.00      1.00       332

    accuracy                           1.00       732
   macro avg       1.00      1.00      1.00       732
weighted avg       1.00      1.00      1.00       732

confusion_matrix:-  [[400   0]
 [  0 332]]
accuracy_score:-  1.0
Feature importances:  [0.24987191 0.13705199 0.21778632 0.00377071 0.00469334 0.2614304
 0.12462163 0.00077369]

In [133]:
pred = rf.predict(n_x)
print('Classification Report:- \n',classification_report(pred, n_y))
print("confusion_matrix:- ", confusion_matrix(n_y, pred))
print("accuracy_score:- ",accuracy_score(n_y, pred))

Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       998
           1       0.00      0.00      0.00         2

    accuracy                           1.00      1000
   macro avg       0.50      0.50      0.50      1000
weighted avg       1.00      1.00      1.00      1000

confusion_matrix:-  [[998   2]
 [  0   0]]
accuracy_score:-  0.998

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [122]:
test3 = [[87, 8.19, 8.35, 4, 8, 5, 3, 0]] # using after polynomail feature 
print(model.predict(test3))

[0]

d:\CODING\ML using Python\Venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [123]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    model,
    x_test,
    y_test,
    n_repeats=10,
    random_state=42
)

for i in range(x_test.shape[1]):
    print(
        x_test.columns[i],
        result.importances_mean[i],
        result.importances_std[i]
    )

IQ 0.12515 0.005890882786136539
Prev_Sem_Result 0.00014999999999998348 0.00022912878474776676
CGPA 0.1397 0.004528796749689709
Academic_Performance 0.0 0.0
Extra_Curricular_Score 0.0 0.0
Communication_Skills 0.14115000000000003 0.0035288099977187765
Projects_Completed 0.08254999999999998 0.004064787817340535
Internship_Experience_Yes 0.0 0.0

In [124]:
from sklearn import model_selection
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance
result = permutation_importance(
    RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
    ).fit(x_tr, y_tr),
    x_te,
    y_te,
    n_repeats=10,
    random_state=42
)

for i in range(x_te.shape[1]):
    print(x_te.columns[i], result.importances_mean[i])

IQ 0.20204918032786887
Prev_Sem_Result 0.0
CGPA 0.19918032786885248
Academic_Performance 0.0
Extra_Curricular_Score 0.0
Communication_Skills 0.21284153005464482
Projects_Completed 0.11775956284153007
Internship_Experience_Yes 0.0

In [125]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

scores = cross_val_score(rf, x_train, y_train, cv=cv, scoring="accuracy")
print("RF CV:", scores)
print("Mean:", scores.mean())

RF CV: [0.99875  1.       0.99875  0.999375 1.      ]
Mean: 0.999375

In [126]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        l1_ratio=0,
        C=0.5,
        max_iter=1000
    ))
])

scores = cross_val_score(pipe, x_train, y_train, cv=cv, scoring="accuracy")
print("LogReg CV:", scores)
print("Mean:", scores.mean())

LogReg CV: [0.89625 0.9     0.9175  0.895   0.89125]
Mean: 0.9

In [127]:
from sklearn.linear_model import LogisticRegression

pipe_l1 = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        l1_ratio=1,
        solver="liblinear",
        C=0.5,
        max_iter=1000
    ))
])

scores = cross_val_score(pipe_l1, x_train, y_train, cv=cv, scoring="accuracy")
print("LogReg L1 CV:", scores)
print("Mean:", scores.mean())

LogReg L1 CV: [0.8975   0.9      0.9175   0.896875 0.891875]
Mean: 0.90075

In [128]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_depth=5,
    min_samples_leaf=5,
    min_samples_split=10,
    random_state=42
)

scores = cross_val_score(dt, x_train, y_train, cv=cv, scoring="accuracy")
print("DT CV:", scores)
print("Mean:", scores.mean())

DT CV: [1.      1.      0.99875 1.      1.     ]
Mean: 0.99975

In [129]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

rf.fit(X_train, y_train)
pred = rf.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, pred))

Test accuracy: 1.0

In [130]:
for feat, imp in zip(X.columns, rf.feature_importances_):
    print(feat, imp)

IQ 0.2636074612342594
Prev_Sem_Result 0.13459934148996786
CGPA 0.2044342219818496
Academic_Performance 0.0050692456286991336
Extra_Curricular_Score 0.005210384249903876
Communication_Skills 0.2685415615509646
Projects_Completed 0.11757290706489663
Internship_Experience_Yes 0.0009648767994590036